function generateAboutPage() {
  const file = document.getElementById('resumeUpload').files[0];
  if (!file) return alert('Please upload a resume first!');

  const reader = new FileReader();

  reader.onload = function (event) {
    const rawText = event.target.result;

    const sections = {
      contact: '',
      skills: '',
      certifications: '',
      experience: '',
      summary: '',
    };

    const lines = rawText.split('\n');
    let currentSection = '';

    for (let line of lines) {
      line = line.trim();
      if (/^contact$/i.test(line)) currentSection = 'contact';
      else if (/skills/i.test(line)) currentSection = 'skills';
      else if (/certifications/i.test(line)) currentSection = 'certifications';
      else if (/experience/i.test(line)) currentSection = 'experience';
      else if (/summary/i.test(line)) currentSection = 'summary';
      else if (currentSection) sections[currentSection] += line + '\n';
    }

    const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>About Me</title>
  <style>
    body {
      background: #fff;
      color: #222;
      font-family: Arial, sans-serif;
      padding: 2em;
      max-width: 800px;
      margin: auto;
    }
    h1, h2 {
      border-bottom: 1px solid #ddd;
      padding-bottom: 0.3em;
    }
    section {
      margin-bottom: 2em;
    }
    pre {
      background: #f9f9f9;
      padding: 1em;
      border-radius: 5px;
      overflow-x: auto;
    }
  </style>
</head>
<body>
  <h1>About Me</h1>

  ${sections.summary ? `<section><h2>Summary</h2><p>${sections.summary.replace(/\n/g, '<br>')}</p></section>` : ''}

  ${sections.contact ? `<section><h2>Contact</h2><pre>${sections.contact}</pre></section>` : ''}
  ${sections.skills ? `<section><h2>Skills</h2><pre>${sections.skills}</pre></section>` : ''}
  ${sections.certifications ? `<section><h2>Certifications</h2><pre>${sections.certifications}</pre></section>` : ''}
  ${sections.experience ? `<section><h2>Experience</h2><pre>${sections.experience}</pre></section>` : ''}

  <footer><p style="font-size:0.8em;color:#888;">Generated by PacMacMobile.com</p></footer>
</body>
</html>`;

    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    window.open(url, '_blank');
  };

  reader.readAsText(file);
}
